### ISSUE TITLE
cb2_plug_pms_uddeim not working and prevents CB 2.1 control panel from working

### ISSUE THREAD

**Issue by Quark-Zimmerman** [slabbi/uddeIM#116]
Basically as it says, 
cb2_plug_pms_uddeim not working and prevents Community Builder 2.1 control panel from working , at least when running PHP 8.4 .

The require_once() loading "pms.uddeim.php" crashes silently and no page displayed for any of CP 2.1 (my version is 2.10.0+build.2025.02.10.18.59.11.b0d14120b running on Joomla 3.10)  control panel pages.

The reason is simple - at come point in CB 2.1 they changed the function signature of "cbPMSHandler::sendUserPMS()" to:
`public function sendUserPMS( $toUserId, $fromUserId, $subject, $message, $systemGenerated = false, $fromName = null, $fromEmail = null )
	{
	}`
while in uddeim the signature is till like this:
`function sendUserPMS($toid, $fromid, $subject, $message, $systemGenerated=false, $escaped=false)`

- note last `$fromEmail = null ` missing.

So, the simple fix is to change the signature like this:
`public function sendUserPMS( $toUserId, $fromUserId, $subject, $message, $systemGenerated = false, $fromName = null, $fromEmail = null, $escaped=false)`

and on line 439 make the following change:
`if ($this->sendUserPMS($recip, $sender, $newsub, $newmsg, $systemGenerated=false, null,$escaped=true)) {`

(note null added before last parameter).

Not sure its a proper change as I pass null for email, but at least it makes Community Builder Control panel work properly  and send messages.

**Comment by Quark-Zimmerman** [comment]
One more thing , after fixing above , it start to crash frontend with "can't find _UDDEIM_PM_INBOX" message, looks like admin language php files somehow do not get included

**Comment by joomod** [comment]
hi,
I don't know which versions you are mixing?

1. the actual cb2_plug_pms_uddeim contains 
   `function sendUserPMS($toid, $fromid, $subject, $message, $systemGenerated=false, **$fromName = null, $fromEmail = null**)`

2. you speak about CB 2.1 but I think you mean v2.10.x ??
in your posting you write about Jommla 3.10
_my version is 2.10.0+build.2025.02.10.18.59.11.b0d14120b running on **Joomla 3.10**_

3. uddeim v5.x **does not** contain a ready russian language file,
    when you take some old language files you have to add the new defination manually
(see new_defines_v5+.php in the v5.x language folder)

and YES, you are right, there are misdefinations in the lines for **new v3.6**  
UDDEIM_PM is correct   (I corrected this in the old russian.php files)

btw.
you are welcomed to **upload** a finished **russian** translated file for **v5** :)

**Comment by Quark-Zimmerman** [comment]
1. It's "cb2_plug_pms_uddeim"  ( from [https://github.com/slabbi/uddeIM/tree/main/cb2_plug_pms_uddeim/](https://github.com/slabbi/uddeIM/tree/main/cb2_plug_pms_uddeim/) ) not "cb2_plug_pms_uddeim_j50" , as I use Joomla 3.10  not 5 , or am I misunderstand something ?

2. Yes v2.10.x 

3. Yes, again , ists still not j5 , sorry old site , used uddeIM 4.0 but recently moved to PHP 8 and needed to update to 5.0 as result, but Joomla still 3.10 .

**Comment by joomod** [comment]
I think for this mixed up setting you must take hand on your own for some needed corrections.
for the cb2_plug you have found already

I don't know about the v4 Version as I come here after and only worked for the v5 update.
there will be more errors in v4 especially running with php8 (8.2 has many changes)

and I don't know if v5 will run on a 3.10 system (I hope they have prepared all the changes)
the best way is just to test and if you got errors look in the same file from v4 to see changes

**Comment by Quark-Zimmerman** [comment]
Thanks, I just want to make one thing clear , I am using Joomla 3, should I use "cb2_plug_pms_uddeim" or cb2_plug_pms_uddeim_j50" ?

I mean j50 means it for Joomla 5.x only, right ? So , with 3.10 I am "defaulted" to cb2_plug_pms_uddeim" ?
I am not even trying to run it on Joomla 3.1 , am I wrong ?

The "cb2_plug_pms_uddeim"  runs fine on Joomla 3.0 with CB v2.10.x , besides one problem with CB v2.10.x which I reported above and fixed, and since CB v2.10.x is de facto a standard now I believe the "cb2_plug_pms_uddeim" needs to be updated, right ?

**Comment by joomod** [comment]
I can't remember what I have to change for _j50 version,
mainly it was the use of namrspace definitions and change all JClasses to Classes (without J).
I think Joomla has prepared v3.10 for the namespace use, but not quite shure.
- you can just try the _j50 version, but yes it is basicly for the use with Joomla5.

as CB 2.10 is the very actual version and runs on your J3 means that J3.10 can use J5 scripts.

as I don't know when CB has changed the code it is not clear weather to update the plugin or not.
if you try the _j50 version we can give a hint for users who combine old J3 with the new CB2.10
